version: '3.8'
services:
  api:
    container_name: wiijoy-library-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - node_modules:/usr/src/app/node_modules
    networks:
      - wiijoy-app
  
  postgres:
    container_name: wiijoy-library-db
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglog:/var/log/postgresql
    networks:
      - wiijoy-app

volumes:
  pgdata:
  pglog:
  node_modules:

networks:
  wiijoy-app:
    name: wiijoy-app
    driver: bridge